-- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 07:38:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistcc` DEFAULT CHARACTER SET utf8 ;
USE `sistcc` ;

-- -----------------------------------------------------
-- Table `sistcc`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistcc`.`PROFESSOR` (
  `RM_PROFESSOR` VARCHAR(5) NOT NULL,
  `NOME_PROFESSOR` VARCHAR(45) NOT NULL,
  `EMAIL_PROFESSOR` VARCHAR(45) NOT NULL,
  `SENHA_PROFESSOR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RM_PROFESSOR`),
  UNIQUE INDEX `EMAIL_PROFESSOR_UNIQUE` (`EMAIL_PROFESSOR` ASC) ,
  UNIQUE INDEX `RM_PROFESSOR_UNIQUE` (`RM_PROFESSOR` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistcc`.`TCC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistcc`.`TCC` (
  `ID_TCC` INT NOT NULL,
  `TEMA_TCC` VARCHAR(50) NOT NULL,
  `ANO_TCC` YEAR NOT NULL,
  `RESUMO_TCC` VARCHAR(45) NOT NULL,
  `ARQUIVO_TCC` VARCHAR(45) NOT NULL,
  `PROFESSOR_RM_PROFESSOR` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID_TCC`),
  UNIQUE INDEX `idTCC_UNIQUE` (`ID_TCC` ASC) ,
  INDEX `fk_TCC_PROFESSOR1_idx` (`PROFESSOR_RM_PROFESSOR` ASC) ,
  CONSTRAINT `fk_TCC_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_RM_PROFESSOR`)
    REFERENCES `sistcc`.`PROFESSOR` (`RM_PROFESSOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistcc`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistcc`.`ALUNO` (
  `RM_ALUNO` VARCHAR(5) NOT NULL,
  `NOME_ALUNO` VARCHAR(50) NOT NULL,
  `EMAIL_ALUNO` VARCHAR(50) NOT NULL,
  `SENHA_ALUNO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`RM_ALUNO`),
  UNIQUE INDEX `RM_ALUNO_UNIQUE` (`RM_ALUNO` ASC) ,
  UNIQUE INDEX `EMAIL_ALUNO_UNIQUE` (`EMAIL_ALUNO` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistcc`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistcc`.`CURSO` (
  `ID_CURSO` INT NOT NULL,
  `NOME_CURSO` VARCHAR(50) NOT NULL,
  `EIXO_CURSO` VARCHAR(25) NOT NULL,
  UNIQUE INDEX `ID_CURSO_UNIQUE` (`ID_CURSO` ASC) ,
  PRIMARY KEY (`ID_CURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistcc`.`TCC_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistcc`.`TCC_ALUNO` (
  `TCC_ID_TCC` INT NOT NULL,
  `ALUNO_RM_ALUNO` VARCHAR(5) NOT NULL,
  `ID_TCC_ALUNO` INT NOT NULL,
  PRIMARY KEY (`ID_TCC_ALUNO`),
  INDEX `fk_TCC_has_ALUNO_ALUNO1_idx` (`ALUNO_RM_ALUNO` ASC) ,
  INDEX `fk_TCC_has_ALUNO_TCC1_idx` (`TCC_ID_TCC` ASC) ,
  CONSTRAINT `fk_TCC_has_ALUNO_TCC1`
    FOREIGN KEY (`TCC_ID_TCC`)
    REFERENCES `sistcc`.`TCC` (`ID_TCC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TCC_has_ALUNO_ALUNO1`
    FOREIGN KEY (`ALUNO_RM_ALUNO`)
    REFERENCES `sistcc`.`ALUNO` (`RM_ALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistcc`.`CURSO_ALUNOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistcc`.`CURSO_ALUNOS` (
  `CURSO_ID_CURSO` INT NOT NULL,
  `ALUNO_RM_ALUNO` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CURSO_ID_CURSO`, `ALUNO_RM_ALUNO`),
  INDEX `fk_CURSO_has_ALUNO_ALUNO1_idx` (`ALUNO_RM_ALUNO` ASC) ,
  INDEX `fk_CURSO_has_ALUNO_CURSO1_idx` (`CURSO_ID_CURSO` ASC) ,
  CONSTRAINT `fk_CURSO_has_ALUNO_CURSO1`
    FOREIGN KEY (`CURSO_ID_CURSO`)
    REFERENCES `sistcc`.`CURSO` (`ID_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_has_ALUNO_ALUNO1`
    FOREIGN KEY (`ALUNO_RM_ALUNO`)
    REFERENCES `sistcc`.`ALUNO` (`RM_ALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
